### PR TITLE
Allow showing of games less than 30 seconds

### LINKED ISSUE #78: Add option to change the number of game-seconds that .slp files are filtered by
Right now the browser always filters games shorter than 30sec. This value ought be modifiable. Perhaps something interesting happened during a quick handwarmer.  
I tried implementing it myself, but I have no idea how react works, to be honest.  
https://github.com/kleutzinger/slippi-desktop-app/commit/5867ec5be334823295ee5422dc260a81eeebaf13  
the form to modify the value is mostly nonfuctional/wrong, but other two files are probably close.  

Plj0VB5

### PR DESCRIPTION
**Pull request by vinceau**
Fixes #78 

This PR adds the following:

* a "Click to show all" button which allows the showing of games which have been filtered due to being less than 30 seconds
* the ability to reveal a file in the default file explorer when clicking on the file name

The setting is stored in the local component state which means the option to filter/show is reset back to the default (which is to filter) whenever the component is unmounted.

### Screenshot

screenshot

### CODE REVIEW

**Comment by JLaferri** [comment]
Trying to think of text that seems more actionable. Like "Click to show all"?

**Comment by vinceau** [comment]
> 
> 
> Trying to think of text that seems more actionable. Like "Click to show all"?

How's "Show all replays"? Isn't "Show" already an action?

**Comment by NikhilNarayana** [comment]
I would like to see it as clear button, I'm worried users won't realize that text is interactable

**Comment by vinceau** [comment]
> 
> 
> I would like to see it as an obvious button, I'm worried users won't realize that text is interactable

I intentionally didn't want to spend too much time on the styling since I think you guys would have a better idea of what you want the button to look like and what kinda aesthetics you're after.

**Comment by JLaferri** [comment]
Yeah I think what Nikki mentioned is why I wanted to add the word "Click". But it's a pretty small thing, I'm content enough pushing it as is, UX-wise. I trust you enough to not have to go through the code too deeply lol

**Comment by vinceau** [comment]
Changed it to "Click to show all" but I haven't changed the styles. Hopefully it's still obvious enough to users.

**Comment by JLaferri** [comment]
What does it look like after you click the button in the case where you:
1. Didn't have corrupt replays
2. Did have corrupt replays

**Comment by vinceau** [comment]
> What does it look like after you click the button in the case where you:
> 
>     1. Didn't have corrupt replays
> 
>     2. Did have corrupt replays

In both cases, the entire banner is hidden after the user clicks "Click to show all". In case number 2 we probably want to keep the banner to indicate the number of corrupted replays but the text copy would need to change.

**Comment by vinceau** [comment]
Updated the banner to show this in the case that the button has been clicked but there are still corrupted files which were filtered.

screenshot

**Comment by NikhilNarayana** [comment]
LGTM

**Pull request merged**
