### PR TITLE
added rough search functionality

### PR DESCRIPTION
**Pull request by agiera**
Displays files where each term (separated by spaces) in the search matches a player or character in the game. A term matches a property if the property starts with the term (case insensitive).

Needs some front end work but it works.
There's a ~1 sec lag searching ~600 files. It might be a good idea to add a submit button. Either that or switch to mysql to store file metadata. That would also get rid of the "Loading Files..." screen.
Might be a good idea to refactor some functions into a `slippiFileUtils` library.

### CODE REVIEW

**Comment by JLaferri** [comment]
Hey, thanks for contributing. I'm focused on some other work atm but I will take a good look at this later. Is there any way you could upload some screenshots showing off the functionality? Thanks.

**Comment by agiera** [comment]
No problem, hope this is useful
https://drive.google.com/file/d/197A4IvJjNoLDhHEysBQgcXzj944bdKpC/view?usp=sharing

**Comment by davidtranhq** [comment]
I'm working on something similar right now. Is there a reason the conflict was not resolved and this was not merged?

**Comment by IvantheTricourne** [comment]
Is there any plans on updating this? This functionality would be very useful.

**Comment by seanlaguna** [comment]
Looks like someone else is picking this up at https://github.com/project-slippi/slippi-desktop-app/pull/97!

**Comment by NikhilNarayana** [comment]
only accepting PRs for the rewrite at this point

**Pull request closed without merging**
