### PR TITLE
Add select all functionality

### PR DESCRIPTION
**Pull request by vmaggioli**
Originally intended to be an auto "play all" feature, but with the queue feature already being merged in I've piggybacked off of it and just made a "select all" for it.

[Trello](https://trello.com/c/Fxes0Izs/118-play-all-button-to-play-all-files-in-a-folder-in-a-row)

Pre-select
image

Post-select
image

### CODE REVIEW

**Comment by JLaferri** [comment]
Instead of being a constantly floating element, I kind of figured the UI should be closer to what you see in gmail.

In other words:
1. A checkbox in the top-left that resembles the other checkboxes that when clicked, will select everything
2. When something is selected, clicking that checkbox will de-select everything

**Comment by vmaggioli** [comment]
Got it, I'll switch the select all button to another check box in the empty grid item next to "Details"

**Comment by vmaggioli** [comment]
Force pushes were for rebase and rebase issue correction

**Comment by vmaggioli** [comment]
Switched persistent button to a checkbox in the table, similar to gmail. Currently still working on select+click functionality as requested by @JLaferri.
image

image

**Comment by JLaferri** [comment]
Looks good. Is de-select working? If so can probably remove the clear button.

As far as minor UI stuff, I might suggest increasing the font size a small amount of "Details" and "Time" headers and bottom aligning them

**Comment by vmaggioli** [comment]
De-select is working as well, but I’d imagine we’d want to keep the clear as somebody can mark a lot of files but not all of them and then want to clear their selections

**Comment by vmaggioli** [comment]
Also looking through the CSS it looks like the padding from the bottom for the headers is dynamically calculated by the table component we're using, so I'm not sure if we want to start messing with that

**Comment by vmaggioli** [comment]
Adjusted table header font size from original 1 em to 1.2 em
image

**Comment by JLaferri** [comment]
For the bottom align thing, you might want to browse the semantic UI docs:
https://react.semantic-ui.com/collections/table/

If you click on Table.Cell, you will see the following:
image

That means that on the HeaderCell react element you can set the property `verticalAlign="bottom"` and it will automatically use bottom alignment without writing any custom CSS. It might help to look through the docs generally because semantic UI is used fairly heavily throughout and it helps to know where you can avoid writing CSS.

**Comment by vmaggioli** [comment]
Force pushed due to forgetting to remove commented out testing code

**Comment by vmaggioli** [comment]
Let me know if I'm reading it wrong, but it looks like `verticalAlign` is only for `Table.Cell` and not `Table.HeaderCell`. I tried their coding examples on their and it worked fine for Cells but didn't seem to do anything for HeaderCells. Also I've added the shift select functionality, please check out the branch and tinker with it to see if it behaves how you're expecting.

**Comment by JLaferri** [comment]
I tested it myself, it works on HeaderCell too. I imagine HeaderCell supports all of the Cell properties

**Comment by JLaferri** [comment]
Though it does seem like `verticalAlign` bottom might be the default anyway...

**Pull request closed without merging**
